# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'caralho.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from dataclasses import dataclass
from re import S
import produtos
from PyQt5 import QtCore, QtGui, QtWidgets


@dataclass
class Item:
    image: str
    quantity: int
    price: float
    index: int


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 670)

        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(338, 30, 123, 41))
        font = QtGui.QFont()
        font.setFamily("Nike 200204")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(610, 580, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(610, 600, 47, 13))
        self.label_3.setObjectName("label_3")

        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(60, 630, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(650, 640, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")

        self.scroll = QtWidgets.QScrollArea(Dialog)
        self.widgetScroll = QtWidgets.QWidget()
        self.vBox = QtWidgets.QVBoxLayout()

        self.widgetScroll.setLayout(self.vBox)

        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.widgetScroll.sizePolicy().hasHeightForWidth())

        self.widgetScroll.setSizePolicy(sizePolicy)

        self.scroll.setWidget(self.widgetScroll)

        self.scroll.setGeometry(QtCore.QRect(60, 100, 680, 450))
        self.scroll.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scroll.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scroll.setWidgetResizable(True)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "CARRINHO"))
        self.label_2.setText(_translate("Dialog", "Subtotal"))
        self.label_3.setText(_translate("Dialog", "Total"))
        self.pushButton.setText(_translate("Dialog", "Voltar"))
        self.pushButton_2.setText(_translate("Dialog", "Finalizar"))

    def addItem(self, item: Item):
        item1LayoutWidget = QtWidgets.QWidget()

        item1LayoutWidget.setFixedSize(QtCore.QSize(678, 80))

        item1Layout = QtWidgets.QHBoxLayout(item1LayoutWidget)
        item1Layout.setContentsMargins(0, 0, 0, 0)

        item1Image = QtWidgets.QLabel(item1LayoutWidget)
        item1Image.setText("")
        item1Image.setStyleSheet(
            f"image: url({item.image});")

        item1quantity = QtWidgets.QSpinBox(item1LayoutWidget)
        item1quantity.setMinimum(1)
        item1quantity.setValue(item.quantity)

        item1Preco = QtWidgets.QLabel(item1LayoutWidget)
        preco_str = f'{item.price * item.quantity:.2f}'.replace('.', ',')
        item1Preco.setText(f"R$ {preco_str}")
        item1Preco.setStyleSheet("font: 75 12pt \"Arial\";")
        item1Preco.setAlignment(QtCore.Qt.AlignCenter)

        item1Layout.addWidget(item1Image)
        item1Layout.addWidget(item1quantity)
        item1Layout.addWidget(item1Preco)

        self.vBox.addWidget(item1LayoutWidget)


if __name__ == "__main__":
    import sys
    items = [
        Item(":/produtos/bones/One piece, Naruto, Simpsons/onepiece-branco-bone.png", 5, 50.00, 0),
        Item(":/produtos/bones/One piece, Naruto, Simpsons/simpsons-preto-bone.png", 2, 20.00, 1),
        Item(":/produtos/bones/One piece, Naruto, Simpsons/simpsons-preto-bone.png", 2, 20.00, 2),
        Item(":/produtos/bones/One piece, Naruto, Simpsons/simpsons-preto-bone.png", 2, 20.00, 3),
        Item(":/produtos/bones/One piece, Naruto, Simpsons/simpsons-preto-bone.png", 2, 20.00, 4),
        Item(":/produtos/bones/One piece, Naruto, Simpsons/simpsons-preto-bone.png", 2, 20.00, 5),
        Item(":/produtos/bones/One piece, Naruto, Simpsons/simpsons-preto-bone.png", 2, 20.00, 6),
        Item(":/produtos/bones/One piece, Naruto, Simpsons/simpsons-preto-bone.png", 2, 20.00, 7),
        Item(":/produtos/bones/One piece, Naruto, Simpsons/simpsons-preto-bone.png", 2, 20.00, 8),
        Item(":/produtos/bones/One piece, Naruto, Simpsons/simpsons-preto-bone.png", 2, 20.00, 9),
        Item(":/produtos/bones/One piece, Naruto, Simpsons/simpsons-preto-bone.png", 2, 20.00, 10),
        Item(":/produtos/bones/One piece, Naruto, Simpsons/simpsons-preto-bone.png", 2, 20.00, 11),
        Item(":/produtos/bones/One piece, Naruto, Simpsons/simpsons-preto-bone.png", 2, 20.00, 12),
        Item(":/produtos/bones/One piece, Naruto, Simpsons/simpsons-preto-bone.png", 2, 20.00, 13),
        Item(":/produtos/bones/One piece, Naruto, Simpsons/simpsons-preto-bone.png", 2, 20.00, 14),
        Item(":/produtos/bones/One piece, Naruto, Simpsons/simpsons-preto-bone.png", 2, 20.00, 15),
        Item(":/produtos/bones/One piece, Naruto, Simpsons/simpsons-preto-bone.png", 2, 20.00, 16),
        Item(":/produtos/bones/One piece, Naruto, Simpsons/simpsons-preto-bone.png", 2, 20.00, 17),
        Item(":/produtos/bones/One piece, Naruto, Simpsons/simpsons-preto-bone.png", 2, 20.00, 18),
        Item(":/produtos/bones/One piece, Naruto, Simpsons/simpsons-preto-bone.png", 2, 20.00, 19),
        Item(":/produtos/bones/One piece, Naruto, Simpsons/simpsons-preto-bone.png", 2, 20.00, 20),
    ]

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)

    for item in items:
        ui.addItem(item)

    Dialog.show()
    sys.exit(app.exec_())
