# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'caralho.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from dataclasses import dataclass
import json
import os

import produtos
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Carrinho(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 670)

        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(338, 30, 123, 41))
        font = QtGui.QFont()
        font.setFamily("Nike 200204")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(610, 580, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(610, 600, 47, 13))
        self.label_3.setObjectName("label_3")

        self.button_voltar = QtWidgets.QPushButton(Dialog)
        self.button_voltar.setGeometry(QtCore.QRect(60, 630, 75, 23))
        self.button_voltar.setObjectName("pushButton")
        self.button_finalizar = QtWidgets.QPushButton(Dialog)
        self.button_finalizar.setGeometry(QtCore.QRect(650, 640, 75, 23))
        self.button_finalizar.setObjectName("pushButton_2")

        self.scroll = QtWidgets.QScrollArea(Dialog)
        self.widgetScroll = QtWidgets.QWidget()
        self.vBox = QtWidgets.QVBoxLayout()

        self.widgetScroll.setLayout(self.vBox)

        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.widgetScroll.sizePolicy().hasHeightForWidth())

        self.widgetScroll.setSizePolicy(sizePolicy)

        self.scroll.setWidget(self.widgetScroll)

        self.scroll.setGeometry(QtCore.QRect(60, 100, 680, 450))
        self.scroll.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scroll.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scroll.setWidgetResizable(True)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "CARRINHO"))
        self.label_2.setText(_translate("Dialog", "Subtotal"))
        self.label_3.setText(_translate("Dialog", "Total"))
        self.button_voltar.setText(_translate("Dialog", "Voltar"))
        self.button_finalizar.setText(_translate("Dialog", "Finalizar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Carrinho()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
