# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'carrinho.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Carrinho(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(700, 400)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(280, 10, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Nike 200204")
        font.setPointSize(6)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.planilha_produtos = QtWidgets.QTableWidget(Dialog)
        self.planilha_produtos.setGeometry(QtCore.QRect(20, 90, 651, 192))
        self.planilha_produtos.setObjectName("planilha_produtos")
        self.planilha_produtos.setColumnCount(3)
        self.planilha_produtos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.planilha_produtos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.planilha_produtos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.planilha_produtos.setHorizontalHeaderItem(2, item)
        self.planilha_produtos.horizontalHeader().setDefaultSectionSize(215)
        self.botao_comprar = QtWidgets.QPushButton(Dialog)
        self.botao_comprar.setGeometry(QtCore.QRect(500, 350, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Nike 200204")
        font.setPointSize(7)
        self.botao_comprar.setFont(font)
        self.botao_comprar.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}\n"
"QPushButton:pressed{\n"
"color:black;\n"
"background-color:white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}")
        self.botao_comprar.setObjectName("botao_comprar")
        self.botao_remover_produto = QtWidgets.QPushButton(Dialog)
        self.botao_remover_produto.setGeometry(QtCore.QRect(320, 350, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Nike 200204")
        font.setPointSize(7)
        self.botao_remover_produto.setFont(font)
        self.botao_remover_produto.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}\n"
"QPushButton:pressed{\n"
"color:black;\n"
"background-color:white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color:black;\n"
"}")
        self.botao_remover_produto.setObjectName("botao_remover_produto")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(420, 290, 111, 41))
        self.label.setObjectName("label")
        self.total_valor = QtWidgets.QLabel(Dialog)
        self.total_valor.setGeometry(QtCore.QRect(600, 290, 71, 41))
        self.total_valor.setObjectName("total_valor")
        self.spin_quantidade = QtWidgets.QSpinBox(Dialog)
        self.spin_quantidade.setGeometry(QtCore.QRect(20, 330, 42, 22))
        self.spin_quantidade.setObjectName("spin_quantidade")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:24pt;\">CARRINHO</span></p></body></html>"))
        item = self.planilha_produtos.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Produto"))
        item = self.planilha_produtos.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Quantidade"))
        item = self.planilha_produtos.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Valor"))
        self.botao_comprar.setText(_translate("Dialog", "COMPRAR"))
        self.botao_remover_produto.setText(_translate("Dialog", "REMOVER ITEM"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:24pt;\">TOTAL:</span></p></body></html>"))
        self.total_valor.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:24pt;\">0,00</span></p></body></html>"))
import template.imgicons
import template.produtos

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Carrinho()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
