# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'historicodecompras.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Historico(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(651, 224)
        font = QtGui.QFont()
        font.setPointSize(16)
        Dialog.setFont(font)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(150, 20, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Nike 200204")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.link_fiscal = QtWidgets.QCommandLinkButton(Dialog)
        self.link_fiscal.setGeometry(QtCore.QRect(220, 130, 201, 41))
        self.link_fiscal.setObjectName("link_fiscal")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:24pt;\">HISTORICO DA COMPRA</span></p></body></html>"))
        self.link_fiscal.setText(_translate("Dialog", "CommandLinkButton"))

import imgicons
import produtos

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Historico()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
